# Generated by Django 4.2.3 on 2023-08-01 01:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-bot'], 'verbose_name': 'Chat', 'verbose_name_plural': 'Chats'},
        ),
        migrations.RemoveField(
            model_name='chat',
            name='created',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='message',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='type',
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rol', models.BooleanField(default=True)),
                ('content', models.TextField(default='', max_length=4096, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chat.chat')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created'],
            },
        ),
    ]
