# Generated by Django 4.2.3 on 2023-07-31 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, verbose_name='bot name')),
                ('description', models.TextField(max_length=500, verbose_name='bot description')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bot',
                'verbose_name_plural': 'Bots',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('tag', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='BotCategories',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bot.bot')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bot.category')),
            ],
            options={
                'verbose_name': 'BotCategories',
                'verbose_name_plural': 'BotsCategories',
                'ordering': ['-bot'],
            },
        ),
    ]
