# Generated by Django 4.2.3 on 2023-08-01 01:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotCharacter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('temperature', models.FloatField(default=0.5)),
                ('max_tokens', models.IntegerField(default=500)),
                ('presence_penalty', models.FloatField(default=0.5)),
                ('frequency_penalty', models.FloatField(default=0.5)),
                ('stream', models.BooleanField(default=False)),
                ('first_message', models.CharField(default='', max_length=512)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bot.bot')),
            ],
        ),
        migrations.CreateModel(
            name='BotMessages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('content', models.CharField(default='', max_length=1024)),
                ('rol', models.BooleanField(default=True)),
                ('bot_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bot.botcharacter')),
            ],
        ),
    ]
